FROM debian:jessie
MAINTAINER Radern <spam@radern.com>

RUN apt-get update && apt-get install -y vim apache2 php5 libapache2-mod-php5 php5-mysql php5-xdebug

# variables environment
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_SITE /var/www/site

RUN mkdir -p $APACHE_RUN_DIR $APACHE_LOCK_DIR $APACHE_LOG_DIR $APACHE_SITE

# tracer toutes les erreurs PHP
RUN sed -i -e 's/^error_reporting\s*=.*/error_reporting = E_ALL/' /etc/php5/apache2/php.ini
RUN sed -i -e 's/^display_errors\s*=.*/display_errors = On/' /etc/php5/apache2/php.ini

ADD ./20-xdebug.ini /etc/php5/apache2/conf.d/

# personnal conf file
ADD ./fichier.conf /etc/apache2/sites-available/
RUN a2ensite fichier.conf
RUN a2dissite 000-default.conf
RUN a2enmod rewrite
RUN a2enmod expires
RUN a2enmod headers
RUN a2enmod cgi

# persistent
EXPOSE 80
ENTRYPOINT ["/usr/sbin/apache2"]
CMD ["-D", "FOREGROUND"]
